#!/usr/bin/python3

from pause import dot
from EmailMsg import Send_Email
from prompter import yesno
from IPy import IP
from netaddr import *
import pprint
import sys
import getpass
import time

TS =  time.sleep
orig_stdout = sys.stdout

print("Config generated by",getpass.getuser(), "on", time.strftime("%x"))

while True:
        try:
                TODO = int(input("What would you like to do?\n\n 1. Configure a firewall\n 2. Configure a switch\n 3. Configure both a firewall and switch\n Please enter your selection Number: "))
                if TODO <= 3 and TODO != 0:
                        False
                else:
                        true
                break
        except:
                print ("Checking...", end="")
                dot()
                #d = dot.hello
                #print(d)
                print("[Done]")
                print("Come On!  That wasn't even an option.  Try again...")
                
print ("Starting...", end="")
dot()
if TODO == "1":
        TODO = "firewall"
        print(TODO," script...[DONE]")
elif TODO == "2":
        TODO = "switch"
        print(TODO," script...[DONE]")
else:
        TODO = "firwall+switch"
        print(TODO," script...[DONE]")

while True:
        try:
                MOD = int(input("Choose a Model\n\n 1. 55XX-X\n 2. 5506-X\n 3. 5506-X(SW)\n 4. 55XX\n 5. 5505\n Please enter your selection Number: "))
                if MOD <= 5 and MOD != 0:
                        False
                else:
                        true
                break
        except:
                print ("Checking...", end="")
                dot()
                print("[Done]")
                print("Come On!  That wasn't even an option.  Try again...")
                
print ("Applying...", end="")
dot()
if MOD == "1":
        MOD = "55XX-X"
        print("Setting model to ", MOD)
elif MOD == "2":
        MOD = "5506-X"
        print("Setting model to ", MOD)
elif MOD == "3":
        MOD = "5506-X(SW)"
        print("Setting model to ", MOD)
elif MOD == "4":
        MOD = "55XX"
        print("Setting model to ", MOD)
else:
        MOD = "5505"
        print("Setting model to ", MOD)

while True:
        try:
                DIV = int(input("Choose a Division\n 1. YOH\n 2. SOC\n 3. ECM\n 4. M&H\n 5. DZMG\n Please enter your selection Number: "))
                if DIV <= 5 and DIV != 0:
                        False
                else:
                        true
                break
        except:
                print ("Checking...", end="")
                dot()
                print("[Done]")
                print("Really, your an Engineer and you can't answer a simple question. That wasn't even an option.  Try again...")
                
print ("Applying...", end="")
dot()
if DIV == "1":
        DIV = "YOH"
        print("Setting Division to ", DIV)

elif DIV == "2":
        DIV = "SOC"
        print("Setting Division to ", DIV)
elif DIV == "3":
        DIV = "ECM"
        print("Setting Division to ", DIV)
elif DIV == "4":
        DIV = "MH"
        print("Setting Division to ", DIV)
else:
        DIV = "DZMG" 
        print("Setting Division to ", DIV)


CITY = input("Please enter The City: ")
print ("Applying...", end="")
dot()
print ("Setting City to ", CITY)

while True:
        try:
                CRYPT = int(input("Please enter The cryptomap Number: "))
                break
        except:
                print ("Checking...", end="")
                dot()
                print("[Done]")
                print("Oops!  That was no valid number.  Try again...")
                
print ("Applying...", end="")
dot()
print ("Setting Cryptomap to ", CRYPT)

ARPT = input("Please enter The Airport Code: ")
print ("Applying...", end="")
dot()
print ("Setting Airport Code to ", ARPT)

HA = yesno('Will this be a HA Pair?', default='no')
print ("Applying...", end="")
dot()
print ("Setting HA Pair in config")

DHCP = yesno('Enable DHCP for the DATA VLAN?', default='no')
print ("Applying...", end="")
dot()
print ("Setting DATA DHCP config")

VOICE = yesno('Enable DHCP for the VOICE VLAN?', default='no')
print ("Applying...", end="")
dot()
print ("Setting Voice interface in config")

while True:
	try:
		WAN = input("Enter the WAN IP: ")
		WMASK = input("Enter the WAN Mask using CIDR notation(/X): ")
		IP(WAN)
		WANIP = IPNetwork(WAN+WMASK)
		WANMASK = WANIP.netmask
		if IP(WAN).iptype() == 'PRIVATE':
			true
		else:
			False
		break
	except:
                print ("Checking...", end="")
                dot()
                print("[Done]")
                print("You have entered an invalid IP address.  Try again...")

print ("Applying...", end="")
dot()
print ("Setting WAN IP to ", WAN, WANMASK)

while True:
        try:
                LAN = input("Enter the LAN IP(Should be the actual outside interface IP): ")
                LMASK = input("Enter the LAN Mask using CIDR notation(/X): ")
                IP(LAN)
                LANIP = IPNetwork(LAN+LMASK)
                LANMASK = LANIP.netmask
                if IP(LAN).iptype() == 'PUBLIC':
                        true
                else:
                        False
                break
        except:
                print ("Checking...", end="")
                dot()
                print("[Done]")
                print("You have entered an invalid IP address.  Try again...")

print ("Applying...", end="")
dot()
print ("Setting LAN IP to ", LAN, LANMASK)

#NAME = name.upper()


with open(CITY, 'a') as f:
    sys.stdout = f
    print ("test")

sys.stdout = orig_stdout
f.close()

#Send_Email(DIV,CITY,CRYPT)

